#!/bin/bash

# Activate the virtual environment
source $KTKB_PATH/venv/bin/activate

# Change this to the correct path of your Python main module
cd $KTKB_PATH
PYTHON_MODULE="kantankanban"

# Run the Python module
python3 -m $PYTHON_MODULE "$@"
